<a href="https://colab.research.google.com/github/shubhangisonkar0-commits/PizzaHub-Sales-Analysis/blob/main/mini_project_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/Book1.csv")
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.shape[1] #number of columns

13

In [ ]:
df.shape[0] #number of rows

10000

In [ ]:
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
df.dtypes

CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [ ]:
df.info() #dataset overview

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  int64
 1   Surname          10000 non-null  object
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  object
 4   Gender           10000 non-null  object
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), object(3)
memory usage: 1015.8+ KB

In [ ]:
df.isnull() #checking missing values in each column

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum() #count missing values
#no missing values

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.describe() #Check for Invalid / Outlier Values

,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [ ]:
df[(df['Age']<18)|(df['Age']>100)] #for realistic age
#no invalid ages founded

Empty DataFrame
Columns: [CustomerId, Surname, CreditScore, Geography, Gender, Age, Tenure, Balance, NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary, Exited]
Index: []

In [ ]:
df[(df['CreditScore']<300)|(df['CreditScore']>900)] #credit score range

Empty DataFrame
Columns: [CustomerId, Surname, CreditScore, Geography, Gender, Age, Tenure, Balance, NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary, Exited]
Index: []

In [ ]:
df[(df['Balance']<0)] #balance cannot be negative

Empty DataFrame
Columns: [CustomerId, Surname, CreditScore, Geography, Gender, Age, Tenure, Balance, NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary, Exited]
Index: []

In [ ]:
#Dataset is clean and valid

#For data manipulation

In [ ]:
df[['CustomerId', 'Age', 'Balance', 'Exited']] #Selecting specific columns

      CustomerId  Age    Balance  Exited
0       15634602   42       0.00       1
1       15647311   41   83807.86       0
2       15619304   42  159660.80       1
3       15701354   39       0.00       0
4       15737888   43  125510.82       0
...          ...  ...        ...     ...
9995    15606229   39       0.00       0
9996    15569892   35   57369.61       0
9997    15584532   36       0.00       1
9998    15682355   42   75075.31       1
9999    15628319   28  130142.79       0

[10000 rows x 4 columns]

In [ ]:
df[(df['Exited']==1)] #Customers who exited from bank

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
5,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
7,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
16,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9981,15672754,Burbidge,498,Germany,Male,42,3,152039.70,1,1,1,53445.17,1
9982,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9991,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9997,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1

In [ ]:
df[(df['IsActiveMember']==1)&(df['Balance']>100000) ] #Active customers with high balance

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
8,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
15,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
26,15736816,Young,756,Germany,Male,36,2,136815.64,1,1,1,170041.95,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9966,15590213,Ch'en,479,Spain,Male,35,4,125920.98,1,1,1,20393.44,0
9967,15603794,Pugliesi,623,France,Male,48,5,118469.38,1,1,1,158590.25,0
9981,15672754,Burbidge,498,Germany,Male,42,3,152039.70,1,1,1,53445.17,1
9986,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0

In [ ]:
df.sort_values(by='Balance', ascending=False) #sort by balance(highest first)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
2092,15757408,Lo,655,Spain,Male,38,3,250898.09,3,0,1,81054.00,1
3280,15715622,To Rot,583,France,Female,57,3,238387.56,1,0,1,147964.99,1
8733,15714241,Haddon,749,Spain,Male,42,9,222267.63,1,0,0,101108.85,1
3588,15571958,McIntosh,489,Spain,Male,40,3,221532.80,1,1,0,171867.08,0
6717,15586674,Shaw,663,Spain,Female,58,5,216109.88,1,0,1,74176.71,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,15633648,Jideofor,696,Spain,Female,51,5,0.00,2,1,0,55022.43,0
630,15712403,McMillan,589,France,Female,61,1,0.00,1,1,0,61108.56,1
3687,15626806,Labrador,668,France,Female,32,2,0.00,2,1,1,40652.33,0
3685,15642137,Fang,695,Spain,Female,39,5,0.00,2,0,0,102763.69,0
646,15730830,Dale,752,France,Female,30,3,0.00,2,1,1,104991.28,0

In [ ]:
df.rename(columns={'NumOfProducts':'TotalProducts'}, inplace=True) #rename

In [ ]:
df['AgeGroup']= pd.cut(df['Age'],
                       bins=[18,30,45,60,100],
                       labels=['Young', 'Adult','MidAge','Senior'])
#Age group colunm

In [ ]:
#balance category
df['BalanceCategory']= np.where(df['Balance']>100000, 'High', 'Low')

In [ ]:
#covert data type
df['HasCrCard']= df['HasCrCard'].astype('bool')
df['IsActiveMember']= df['IsActiveMember'].astype('bool')

In [ ]:
df[(df['Exited']==1)&(df['Balance']>10000)] #Customers who left & had high balance

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,BalanceCategory
2,15619304,Onio,502,France,Female,42,8,159660.80,3,True,False,113931.57,1,High
5,15574012,Chu,645,Spain,Male,44,8,113755.78,2,True,False,149756.71,1,High
7,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,True,False,119346.88,1,High
16,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,True,False,5097.67,1,High
35,15794171,Lombardo,475,France,Female,45,0,134264.04,1,True,False,27822.99,1,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9975,15666295,Smith,610,Germany,Male,50,1,113957.01,2,True,False,196526.55,1,High
9981,15672754,Burbidge,498,Germany,Male,42,3,152039.70,1,True,True,53445.17,1,High
9982,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,True,False,115146.40,1,High
9991,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,True,False,69384.71,1,Low
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,True,False,92888.52,1,Low

In [ ]:
df.nlargest(10,'EstimatedSalary') #Top 10 customers by salary

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,BalanceCategory
6646,15662021,Lucciano,685,Spain,Female,42,2,0.00,2,False,False,199992.48,0,Low
3580,15634359,Dyer,639,Germany,Female,41,5,98635.77,1,True,False,199970.74,0,Low
4417,15697270,Gannon,608,Spain,Male,27,4,153325.10,1,True,True,199953.33,0,High
9096,15762331,Moss,569,France,Male,37,9,178755.84,1,True,False,199929.17,0,High
8926,15709136,Adams,620,France,Male,28,8,0.00,2,True,True,199909.32,0,Low
5958,15741719,DeRose,540,France,Female,40,3,165298.12,1,False,True,199862.75,0,High
1378,15682834,Johnstone,715,Spain,Female,35,4,40169.88,2,True,True,199857.47,0,Low
6402,15804211,Oluchukwu,719,France,Male,36,3,155423.17,1,True,True,199841.32,0,High
8088,15815656,Hopkins,541,Germany,Female,39,9,100116.67,1,True,True,199808.10,1,High
6125,15687913,Mai,501,Germany,Female,34,7,93244.42,1,False,True,199805.63,0,Low

In [ ]:
df.groupby('Geography')['Balance'].mean() #Average Balance by Geography

Geography
France      62092.636516
Germany    119730.116134
Spain       61818.147763
Name: Balance, dtype: float64

In [ ]:
df.groupby('Gender')['Balance'].mean() #Average Balance by Gender

Gender
Female    75659.369139
Male      77173.974506
Name: Balance, dtype: float64

In [ ]:
df.groupby('Gender')['Balance'].sum() #Total Balance by Gender

Gender
Female    3.437205e+08
Male      4.211384e+08
Name: Balance, dtype: float64

In [ ]:
df.groupby('Geography')['CreditScore'].agg(['max', 'min']) #Maximum & Minimum Credit Score by Geography

           max  min
Geography
France     850  350
Germany    850  350
Spain      850  350

In [ ]:
df.groupby('Exited')['Age'].mean() #Average Age of Customers Who Exited(1) vs Stayed(0)

Exited
0    37.408389
1    44.837997
Name: Age, dtype: float64

In [ ]:
#balance Statistics
df.groupby('Geography')['Balance'].agg(Total_Balance='sum',
                                       Average_balance='mean',
                                       Max_balance='max',
                                       Min_balance='min',
                                       Count_balance='count'
                                       )

,Total_Balance,Average_balance,Max_balance,Min_balance,Count_balance
Geography,,,,,
France,3.113325e+08,62092.636516,238387.56,0.00,5014
Germany,3.004029e+08,119730.116134,214346.96,27288.43,2509
Spain,1.531236e+08,61818.147763,250898.09,0.00,2477

from matplotlib import pyplot as plt
_df_0['Total_Balance'].plot(kind='hist', bins=20, title='Total_Balance')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Average_balance'].plot(kind='hist', bins=20, title='Average_balance')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Max_balance'].plot(kind='hist', bins=20, title='Max_balance')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Min_balance'].plot(kind='hist', bins=20, title='Min_balance')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('Geography').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='Total_Balance', y='Average_balance', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Average_balance', y='Max_balance', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='Max_balance', y='Min_balance', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='Min_balance', y='Count_balance', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_9['Total_Balance'].plot(kind='line', figsize=(8, 4), title='Total_Balance')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['Average_balance'].plot(kind='line', figsize=(8, 4), title='Average_balance')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_11['Max_balance'].plot(kind='line', figsize=(8, 4), title='Max_balance')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_12['Min_balance'].plot(kind='line', figsize=(8, 4), title='Min_balance')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_13['Geography'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_13, x='Total_Balance', y='Geography', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_14['Geography'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_14, x='Average_balance', y='Geography', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_15['Geography'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_15, x='Max_balance', y='Geography', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_16['Geography'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_16, x='Min_balance', y='Geography', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
df.groupby('TotalProducts')['CustomerId'].count() #Number of Customers by Product Count

TotalProducts
1    5084
2    4590
3     266
4      60
Name: CustomerId, dtype: int64

In [ ]:
df.groupby('Geography')['Exited'].mean() #Churn Rate by Geography

Geography
France     0.161548
Germany    0.324432
Spain      0.166734
Name: Exited, dtype: float64

In [ ]:
#1: Geography vs Balance

# Customers from different geographical regions show significant differences in average account balance,
# indicating regional economic variation.

In [ ]:
#2: High Balance Customers & Churn

#Customers with higher balances tend to exit less frequently, suggesting that high-value customers are more loyal to the bank.

In [ ]:
#3: Age and Customer Exit

#The average age of customers who exited is higher than those who stayed, indicating older customers are more likely to leave.

In [ ]:
#4: Product Usage Pattern

# Most customers own 1–2 bank products, and customers with more products tend to show lower churn,
# implying higher engagement reduces exit probability.

In [ ]:
#5: Geography-Based Churn Rate

#Certain regions show a higher churn rate, suggesting the bank may need targeted retention strategies in those locations.

In [ ]:
#6: Credit Score Distribution

#Customers across all regions have a similar credit score range, indicating credit risk is evenly spread.

In [ ]:
#This project applied grouping and aggregation techniques using Pandas to analyze customer behavior.
#The analysis revealed patterns in balance distribution, churn behavior, and regional differences.
#Insights derived from the data can help banks improve customer retention strategies and target high-risk groups effectively.